### ISSUE TITLE
antsibull-changelog release command fails with No such file or directory: 'ansible-doc'

### ISSUE THREAD

**Issue by sameer666** [ansible-community/antsibull-changelog#63]
When trying to run the antsibull-changelog release command inside the collection directory after the changelog folder is created, the command breaks with the following error:

Traceback (most recent call last):
  File "/home/sameer/my-project-env/lib/python3.8/site-packages/antsibull_changelog/cli.py", line 239, in run
    return arguments.func(arguments)
  File "/home/sameer/my-project-env/lib/python3.8/site-packages/antsibull_changelog/cli.py", line 452, in command_release
    plugins = load_plugins(paths=paths, collection_details=collection_details,
  File "/home/sameer/my-project-env/lib/python3.8/site-packages/antsibull_changelog/plugins.py", line 423, in load_plugins
    plugins_data = _refresh_plugin_cache(paths, collection_details, version, use_ansible_doc)
  File "/home/sameer/my-project-env/lib/python3.8/site-packages/antsibull_changelog/plugins.py", line 380, in _refresh_plugin_cache
    _load_collection_plugins(plugins_data, paths, collection_details, use_ansible_doc)
  File "/home/sameer/my-project-env/lib/python3.8/site-packages/antsibull_changelog/plugins.py", line 350, in _load_collection_plugins
    plugins_data['plugins'][plugin_type] = load_plugin_metadata(
  File "/home/sameer/my-project-env/lib/python3.8/site-packages/antsibull_changelog/plugins.py", line 298, in load_plugin_metadata
    plugins_data = run_ansible_doc(paths, playbook_dir, plugin_type, plugins_list)
  File "/home/sameer/my-project-env/lib/python3.8/site-packages/antsibull_changelog/plugins.py", line 267, in run_ansible_doc
    output = subprocess.check_output(command)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ansible-doc'

**Comment by felixfontein** [comment]
Did you install ansible-core or ansible-base?

**Comment by sameer666** [comment]
After installing ansible-core it works. Thanks.

**Comment by sameer666** [comment]
After installing ansible-core it works. Thanks.
